### ISSUE TITLE
Add numbers and hover text to progress bar

### ISSUE THREAD

**Issue by nathanmwilliams** [townhallproject/whip-count#3]
Like townhallpledge.com bar. Numbers on top of the colors, plus hover text.

**Comment by meganrm** [comment]
i added numbers, but the hover text seemed pretty redundant to me because the tittles are already there in the same color.

**Comment by nathanmwilliams** [comment]
Gotcha. I think it mostly depends on how long the various sections get and how well they line up with the categories above. If, say, the "Consider after E-Day" remains small and the dark purple grows, it might not be intuitive if it's no longer lined up under it.

But no urgency to change now. Thanks!
