### ISSUE TITLE
Add Header 

### ISSUE THREAD

**Issue by nathanmwilliams** [townhallproject/whip-count#4]
Top header above Search bar level:

"SCOTUS Vacancy - Senate Whip Count"

Potential temp banner background here if helpful.
![background banner temp](https://user-images.githubusercontent.com/25805849/93819524-af5ceb00-fc10-11ea-9c90-c535b9bc226a.png)

**Comment by meganrm** [comment]
if this is moslty going to be embedded, I was trying to keep it to about screen height with the idea that header/banner stuff would be on the page that embeds it

**Comment by nathanmwilliams** [comment]
Ah, gotcha. I think in addition to the embedded option we (and probably Indivisible) will have this on a stand-alone site.

**Comment by nathanmwilliams** [comment]
![Uploading ashley banner.png…]()
