### ISSUE TITLE
"4" status coming up as "Undefined" for Bipartisan Infrastructure

### ISSUE THREAD

**Issue by nathanmwilliams** [townhallproject/whip-count#40]
https://www.peopleswhipcount.org/#bipart-infra

![4 undefined](https://user-images.githubusercontent.com/25805849/123483295-56651d80-d5bb-11eb-92f3-f09ee4b3d3f6.png)

**Comment by meganrm** [comment]
for some reason those are getting formatted as `[NUMBER].[TAB][TEXT]` instead of `[NUMBER].[SPACE][TEXT]`. I tried fixing it on the spreadsheet but I couldn't so now the code checks for either a space or a tab
