### ISSUE TITLE
Mouse-over highlight color for text links to Issue pages

### ISSUE THREAD

**Issue by nathanmwilliams** [townhallproject/whip-count#49]
To help convey that "legislative details" and whip count are distinct options. 

![mouseover](https://user-images.githubusercontent.com/25805849/187750558-b7b0dad7-b6b1-407b-8a82-0fcd3d3ea672.png)

**Comment by meganrm** [comment]
I thought that just having it on the issue page itself made more sense anyway so I removed it. But now the cards themself are pretty bland
